# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- script: |
    ng build --prod
  displayName: 'npm build'

- script: |
    npm test
    echo "tests completed"
  displayName: 'npm test'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'dist/karriere'
    ArtifactName: 'angular-cv-compiled'
    publishLocation: 'Container'
  displayName: 'Publish Artifacts'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: 'testresults'
    ArtifactName: 'testresults'
    publishLocation: 'Container'
  displayName: 'Publish test results'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '**/testresults/coverage/*.xml'

- task: PublishTestResults@1
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/testresults/junit/*.xml'

